### ISSUE TITLE
HAProxy templates

### ISSUE THREAD

**Issue by brianlycett** [vfarcic/docker-flow#9]
Hi.

I'd like to be able to use a specific HAProxy template to be dynamically updated in a similar way to consul-template.
That is I need to have multiple backends, each of which are updated for a specific service.

Is there any way of doing that right now?

**Comment by vfarcic** [comment]
That is an interesting and potentially useful feature for many. Please let me know if you have anything more specific in mind. If not, I'll brainstorm a solution, implement it, and get back to you to see whether it fits your scenario. It should be done during the next week.

**Comment by brianlycett** [comment]
Nothing specific, just the ability to use our own consul templates.
We've got a lot of logic in our HAProxy config - routing incoming traffic to different destinations and multiple backends.  This should all work fine via a haproxy container that runs consul-template.
I've got an idea of how I might incorporate blue/green deployment into what we're doing, but it'd be a fair amount of work, most of which you seem to have done already.

**Comment by vfarcic** [comment]
Great! That makes it easy. I'll get back to you once I'm done.

On Thu, May 19, 2016 at 4:37 PM brianlycett <notifications@github.com>
wrote:

> Nothing specific, just the ability to use our own consul templates.
> We've got a lot of logic in our HAProxy config - routing incoming traffic
> to different destinations and multiple backends. This should all work fine
> via a haproxy container that runs consul-template.
> I've got an idea of how I might incorporate blue/green deployment into
> what we're doing, but it'd be a fair amount of work, most of which you seem
> to have done already.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/vfarcic/docker-flow/issues/9#issuecomment-220344141>
>
-- 
Viktor Farcic

Blog:
TechnologyConversations.com

Books:
The DevOps 2.0 Toolkit (http://www.amazon.com/dp/B01BJ4V66M or
https://leanpub.com/the-devops-2-toolkit)
Test-Driven Java Development (
http://www.amazon.com/Test-Driven-Java-Development-Viktor-Farcic-ebook/dp/B00YSIM3SC
)

**Comment by vfarcic** [comment]
This request has been implemented in the release v1.0. Please try it out and let me know whether it fits your use case.

You can find more information in the [Using custom Consul template](https://github.com/vfarcic/docker-flow#using-custom-consul-templates) section of the README.

**Comment by wheelybird** [comment]
Wow.  That was super-quick! Thanks for doing that - I'll give it a spin as soon as I get a chance. :D

**Comment by vfarcic** [comment]
There was an error in the way configs are created and I had to make a new release. The major change is that now two templates are required for each service. One is for the frontend portion of the HAProxy config and the other for the backend.

Please let me know if you need any help setting it up.
